#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ZEUS — Domain & SSL setup
# Ubuntu 20.04 / 22.04 / 24.04
#
# What this does:
#   1. Installs Caddy (auto-HTTPS via Let's Encrypt)
#   2. Reads your running workspaces from instances/
#   3. Generates a Caddyfile:
#        yourdomain.com          → portal (workspace selector)
#        name.yourdomain.com     → each workspace
#   4. Opens UFW ports 80 + 443
#   5. Restarts Caddy + verifies HTTPS is live
#   6. Prints the DNS records you need to add
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'

ZEUS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTANCES_DIR="$ZEUS_ROOT/instances"
CADDY_DIR="$ZEUS_ROOT/caddy"
CADDYFILE="$CADDY_DIR/Caddyfile"

# ── Detect VM public IP ───────────────────────────────────────────────────────
VM_IP=$(curl -sf https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo -e "${BOLD}${CYAN}⚡ ZEUS — Domain & SSL Setup${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  VM public IP: ${BOLD}${VM_IP}${NC}"
echo ""

# ── 1. Get domain ─────────────────────────────────────────────────────────────
read -p "  Enter your domain (e.g. gulli.io or yourdomain.com): " DOMAIN
DOMAIN=$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
if [ -z "$DOMAIN" ]; then echo -e "${RED}No domain provided. Exiting.${NC}"; exit 1; fi

echo ""
echo -e "${CYAN}[1] DNS records to add BEFORE continuing${NC}"
echo "    Add these A records in your domain registrar / VM panel:"
echo ""
echo -e "    ${BOLD}@   (root)   →  ${VM_IP}${NC}   (for the portal)"
echo -e "    ${BOLD}*   (wildcard) →  ${VM_IP}${NC}   (for workspaces)"
echo ""
echo -e "  ${YELLOW}⚠  If your registrar doesn't support wildcard A records, add one"
echo -e "  A record per workspace name instead (shown at the end).${NC}"
echo ""
read -p "  Press Enter once DNS records are set (propagation can take 1-5 min)..."

# ── 2. Install Caddy ──────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}[2] Installing Caddy${NC}"

if command -v caddy &>/dev/null; then
  echo -e "  ${GREEN}Caddy already installed: $(caddy version)${NC}"
else
  echo "  Installing Caddy..."
  sudo apt-get update -qq
  sudo apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    | sudo tee /etc/apt/sources.list.d/caddy-stable.list > /dev/null
  sudo apt-get update -qq
  sudo apt-get install -y -qq caddy
  echo -e "  ${GREEN}Caddy installed: $(caddy version)${NC}"
fi

# ── 3. Discover workspaces ────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}[3] Detecting workspaces${NC}"

declare -A WORKSPACES  # name → port
PORTAL_PORT=3000

if [ -d "$INSTANCES_DIR" ]; then
  for cfg in "$INSTANCES_DIR"/*/instance.json; do
    [ -f "$cfg" ] || continue
    WS_NAME=$(python3 -c "import json; print(json.load(open('$cfg'))['name'])" 2>/dev/null)
    WS_PORT=$(python3 -c "import json; print(json.load(open('$cfg'))['port'])" 2>/dev/null)
    if [ -n "$WS_NAME" ] && [ -n "$WS_PORT" ]; then
      WORKSPACES["$WS_NAME"]="$WS_PORT"
      echo -e "  Found: ${BOLD}${WS_NAME}${NC} → port ${WS_PORT}"
    fi
  done
fi

if [ ${#WORKSPACES[@]} -eq 0 ]; then
  echo -e "  ${YELLOW}No workspaces found. Run install.sh first, then re-run this script.${NC}"
  echo -e "  Continuing with portal-only setup (port ${PORTAL_PORT})."
fi

# ── 4. Generate Caddyfile ─────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}[4] Generating Caddyfile${NC}"

mkdir -p "$CADDY_DIR"

cat > "$CADDYFILE" << CADDYEOF
# ZEUS — Caddyfile
# Auto-generated by scripts/setup-domain.sh
# Edit this file to add/remove workspaces, then run: sudo systemctl reload caddy

# ── Portal (workspace selector) ───────────────────────────────────────────────
${DOMAIN} {
    reverse_proxy localhost:${PORTAL_PORT}

    # Security headers
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options nosniff
        X-Frame-Options SAMEORIGIN
        Referrer-Policy strict-origin-when-cross-origin
    }

    # Compression
    encode gzip

    log {
        output file /var/log/caddy/zeus-portal.log {
            roll_size 10mb
            roll_keep 5
        }
    }
}

CADDYEOF

# Add one block per workspace
for WS_NAME in "${!WORKSPACES[@]}"; do
  WS_PORT="${WORKSPACES[$WS_NAME]}"
  cat >> "$CADDYFILE" << WSEOF
# ── Workspace: ${WS_NAME} ─────────────────────────────────────────────────────
${WS_NAME}.${DOMAIN} {
    reverse_proxy localhost:${WS_PORT}

    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options nosniff
        X-Frame-Options SAMEORIGIN
        Referrer-Policy strict-origin-when-cross-origin
    }

    encode gzip

    log {
        output file /var/log/caddy/zeus-${WS_NAME}.log {
            roll_size 10mb
            roll_keep 5
        }
    }
}

WSEOF
done

echo -e "  ${GREEN}Caddyfile written to: ${CADDYFILE}${NC}"
echo ""
echo "  Preview:"
echo "  ─────────────────────────────────"
cat "$CADDYFILE"
echo "  ─────────────────────────────────"

# ── 5. Install Caddyfile system-wide ─────────────────────────────────────────
echo ""
echo -e "${CYAN}[5] Installing Caddyfile${NC}"
sudo mkdir -p /var/log/caddy
sudo cp "$CADDYFILE" /etc/caddy/Caddyfile
echo -e "  ${GREEN}Copied to /etc/caddy/Caddyfile${NC}"

# Validate
sudo caddy validate --config /etc/caddy/Caddyfile
echo -e "  ${GREEN}Config valid${NC}"

# ── 6. Open firewall ──────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}[6] Firewall${NC}"

if command -v ufw &>/dev/null; then
  sudo ufw allow 80/tcp  comment "HTTP (Caddy ACME challenge)" 2>/dev/null || true
  sudo ufw allow 443/tcp comment "HTTPS (Caddy)"               2>/dev/null || true
  sudo ufw allow 443/udp comment "HTTP/3 (Caddy)"              2>/dev/null || true
  echo -e "  ${GREEN}UFW: opened 80, 443 (tcp+udp)${NC}"
  # Make sure workspace ports are NOT exposed to the internet
  for WS_PORT in "${WORKSPACES[@]}"; do
    sudo ufw deny "$WS_PORT" 2>/dev/null || true
  done
  sudo ufw deny "$PORTAL_PORT" 2>/dev/null || true
  echo -e "  ${GREEN}UFW: internal ports ${PORTAL_PORT} / workspace ports blocked from internet${NC}"
else
  echo -e "  ${YELLOW}ufw not found — open ports 80 and 443 manually in your VM firewall panel${NC}"
fi

# ── 7. Start / reload Caddy ───────────────────────────────────────────────────
echo ""
echo -e "${CYAN}[7] Starting Caddy${NC}"
sudo systemctl enable caddy
sudo systemctl restart caddy
sleep 4

if sudo systemctl is-active --quiet caddy; then
  echo -e "  ${GREEN}Caddy is running${NC}"
else
  echo -e "  ${RED}Caddy failed to start. Check: sudo journalctl -u caddy -n 50${NC}"
  exit 1
fi

# ── 8. Update portal links to use domain ─────────────────────────────────────
echo ""
echo -e "${CYAN}[8] Updating portal to use domain links${NC}"

PORTAL_SCRIPT="$ZEUS_ROOT/portal.py"
if [ -f "$PORTAL_SCRIPT" ]; then
  # Inject DOMAIN env variable into portal service
  PORTAL_SERVICE_FILE="/etc/systemd/system/zeus-portal.service"
  if [ -f "$PORTAL_SERVICE_FILE" ]; then
    sudo sed -i "/^\[Service\]/a Environment=ZEUS_DOMAIN=${DOMAIN}" "$PORTAL_SERVICE_FILE" 2>/dev/null || true
    sudo systemctl daemon-reload
    sudo systemctl restart zeus-portal 2>/dev/null || true
    echo -e "  ${GREEN}Portal service updated with domain${NC}"
  fi
fi

# ── 9. Test HTTPS ─────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}[9] Testing HTTPS${NC}"
sleep 3  # give Caddy a moment for ACME

HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" "https://${DOMAIN}" 2>/dev/null || echo "000")
if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "301" ] || [ "$HTTP_CODE" = "302" ]; then
  echo -e "  ${GREEN}HTTPS is live — got HTTP ${HTTP_CODE} from https://${DOMAIN}${NC}"
else
  echo -e "  ${YELLOW}HTTPS check returned ${HTTP_CODE} — DNS may still be propagating."
  echo -e "  Run this again in a few minutes: curl -I https://${DOMAIN}${NC}"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}${BOLD}⚡ Domain setup complete${NC}"
echo ""
echo -e "  ${BOLD}Portal:${NC}  ${CYAN}https://${DOMAIN}${NC}"
for WS_NAME in "${!WORKSPACES[@]}"; do
  echo -e "  ${BOLD}${WS_NAME}:${NC}     ${CYAN}https://${WS_NAME}.${DOMAIN}${NC}"
done
echo ""
echo -e "  ${BOLD}DNS records needed:${NC}"
echo -e "    A  @   →  ${VM_IP}   (portal)"
for WS_NAME in "${!WORKSPACES[@]}"; do
  echo -e "    A  ${WS_NAME}  →  ${VM_IP}"
done
echo -e "    ${YELLOW}(or a single wildcard A  *  →  ${VM_IP})${NC}"
echo ""
echo -e "  ${BOLD}To add a new workspace later:${NC}"
echo -e "    bash install.sh                 # create workspace"
echo -e "    bash scripts/setup-domain.sh    # re-run this script (safe to re-run)"
echo ""
echo -e "  ${BOLD}Caddy commands:${NC}"
echo -e "    sudo systemctl reload caddy     # apply Caddyfile changes"
echo -e "    sudo journalctl -u caddy -f     # live logs"
echo -e "    sudo caddy validate --config /etc/caddy/Caddyfile"
echo ""
echo -e "  ${BOLD}Caddyfile location:${NC} /etc/caddy/Caddyfile"
echo -e "  ${BOLD}Source template:${NC}    $CADDYFILE"
echo ""
